<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>BGMLoader</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="IllusionLibs.SamabakeScramble.AllPackages" Version="*" />
	</ItemGroup>

	<Import Project="..\Shared\Shared.projitems" Label="Shared" />
</Project>